# ============================================================
# Top-level Makefile
# ============================================================

# ----------------------------
# Build parameters; command-line values take precedence.
# ----------------------------
BUILD    ?= release
STATIC   ?= 1
ASAN     ?= 0
V        ?= 0
PREFIX   ?= /opt/bless-1.0
DESTDIR  ?=
USE_VERSION_H  ?= 1
BL_VERSION ?= 1.0

# ----------------------------
# build mode
# ----------------------------
BUILD_MODE := $(if $(filter 1,$(STATIC)),static,shared)
O          ?= build/$(BUILD)-$(BUILD_MODE)

# ----------------------------
# Paths
# ----------------------------
TOPDIR   := $(CURDIR)
ROOT     := $(abspath .)
ABS_O    := $(abspath $(O))
SRCDIR   := src

# Third-party build settings generated by third_party/.
UP_MK    := $(ROOT)/third_party/third_party.mk

# ----------------------------
# Arguments passed to the src/ sub-make.
# ----------------------------
MAKE_SRC := $(MAKE) -C $(SRCDIR) \
			BLESS_TOPLEVEL_BUILD=1 \
			O="$(ABS_O)" \
			BUILD="$(BUILD)" \
			STATIC="$(STATIC)" \
			ASAN="$(ASAN)" \
			V="$(V)" \
			PREFIX="$(PREFIX)" \
			DESTDIR="$(DESTDIR)" \
			USE_VERSION_H="$(USE_VERSION_H)"

.DEFAULT_GOAL := all

# Generated version header.
VERSION_H = include/version.h

# ============================================================
# clean targets
# ============================================================
# These targets do not need third-party build settings.
ifneq ($(filter clean distclean uninstall help,$(MAKECMDGOALS)),)

.PHONY: clean distclean help
clean:
	@echo "  CLEANING build directory..."
	rm -rf build/

distclean: clean
	$(MAKE) -C third_party clean
	$(MAKE) -C src clean

uninstall:
	+$(MAKE_SRC) uninstall

help:
	@echo "Usage:"
	@echo "  make [target] [VARIABLE=value]"
	@echo ""
	@echo "Targets:"
	@echo "  all        Build everything (default)"
	@echo "  demo       Run a local net_null demo on http://127.0.0.1:8000"
	@echo "  upstream   Prepare third-party libraries only"
	@echo "  install    Install binaries"
	@echo "  clean      Remove build artifacts"
	@echo "  distclean  Clean everything"
	@echo ""
	@echo "Variables:"
	@echo "  STATIC=1|0     Build static or shared (default: 1)"
	@echo "  BUILD=release|debug (default: release)"
	@echo "  PREFIX=/path  Install prefix"

else

# ============================================================
# Build targets
# ============================================================

# ============================================================
# third_party.mk rules
# ============================================================

# Generate the third-party settings when absent.
$(UP_MK):
	@echo "  GEN     $@"
	$(MAKE) -C third_party third_party.mk

# Refresh third-party sources and build settings on request.
.PHONY: update-third-party

update-third-party:
	$(MAKE) -C third_party update-third-party

# CI and debugging entry point for third-party setup.
third_party: $(UP_MK)

# ============================================================
# include third_party output.  The CivetWeb-only integration test has its
# own explicit library dependency and must not trigger unrelated libyaml
# Autotools generation.
# ============================================================
ifneq ($(filter test test/% integration-test,$(MAKECMDGOALS)),)
  # Unit and socket integration tests link their own minimal dependencies.
  # Do not generate third_party.mk (and therefore do not invoke libyaml's
  # Autotools bootstrap) for these DPDK-independent targets.
else
-include $(UP_MK)
endif

GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
GIT_STATE := $(shell \
        if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then \
                if git diff-index --quiet HEAD --; then \
                        echo clean; \
                else \
                        echo dirty; \
                fi; \
        else \
                echo nogit; \
        fi)

# version.h: stable fields only (GIT_COMMIT, BRANCH, STATE do not change
# between invocations).  Uses content-guard — only rewrites the file and
# updates its mtime when the content actually changed.  This prevents a
# cascade rebuild of every translation unit that includes base.h → version.h.
# BUILD_TIME and BUILD_HOST live in src/buildinfo.c (FORCE, one .o only).
FORCE:
$(VERSION_H): FORCE
	@{ \
		echo "#ifndef VERSION_H"; \
		echo "#define VERSION_H"; \
		echo ""; \
		echo "#define BL_VERSION \"$(BL_VERSION)\""; \
		echo "#define GIT_COMMIT \"$(GIT_COMMIT)\""; \
		echo "#define GIT_STATE \"$(GIT_STATE)\""; \
		echo "#define GIT_BRANCH \"$$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)\""; \
		echo "#define BUILD_TYPE \"$(BUILD)\""; \
		echo "#define STATIC $(STATIC)"; \
		echo ""; \
		echo "#endif /* VERSION_H */"; \
	} > $@.tmp
	@if [ ! -f $@ ] || ! cmp -s $@.tmp $@; then \
		echo "  GEN     $@"; \
		mv $@.tmp $@; \
	else \
		rm -f $@.tmp; \
	fi

# ============================================================
# Pass third-party compiler and linker flags to src/.
# ============================================================

export CFLAGS  := $(CFLAGS) $(THIRD_PARTY_CFLAGS)
export LDFLAGS := $(LDFLAGS) $(THIRD_PARTY_LDFLAGS)
export LDLIBS  := $(LDLIBS) $(THIRD_PARTY_LDLIBS)

# ============================================================
# targets
# ============================================================

.PHONY: all demo upstream install uninstall Test

# Default build.
all: $(UP_MK) $(VERSION_H)
	+$(MAKE_SRC)

demo: all
	@echo "  DEMO    dashboard: http://127.0.0.1:8000/entropy"
	@echo "  DEMO    net_null discards packets; stop with Ctrl-C"
	$(ABS_O)/bin/bless conf/config-ci.yaml

upstream: $(UP_MK)

Test:
	+$(MAKE_SRC) Test

install: $(UP_MK)
	+$(MAKE_SRC) install

endif

check:
	readelf -d build/release-static/bin/bless | grep PATH
	llvm-readobj --notes build/release-static/bin/bless
	@echo "more checks:"
	@echo "  objdump -s -j .note.buildinfo build/release-static/bin/bless"
	@echo "  readelf -x .note.buildinfo build/release-static/bin/bless"
	@echo "  readelf -n build/release-static/bin/bless | \
		sed -n '/Displaying notes found in: .note.buildinfo/,/Displaying notes found in:/p' | \
		sed -n '/description data:/,/)/p' | \
		sed -n '/description data:/,/)/p'"

# Unit tests (no DPDK required)
LIBYAML_TEST_SRC := third_party/libyaml/upstream/src/api.c \
	third_party/libyaml/upstream/src/reader.c \
	third_party/libyaml/upstream/src/scanner.c \
	third_party/libyaml/upstream/src/parser.c \
	third_party/libyaml/upstream/src/loader.c \
	third_party/libyaml/upstream/src/writer.c \
	third_party/libyaml/upstream/src/emitter.c \
	third_party/libyaml/upstream/src/dumper.c
LIBYAML_TEST_FLAGS := -I third_party/libyaml/upstream/include \
	-I third_party/libyaml/upstream/src -DHAVE_CONFIG_H=0 \
	-DYAML_VERSION_MAJOR=0 -DYAML_VERSION_MINOR=2 -DYAML_VERSION_PATCH=5 \
	-DYAML_VERSION_STRING='"0.2.5"'

UNIT_TESTS := test/unit/test_dist test/unit/test_core test/unit/test_ipv6 \
	test/unit/test_device test/unit/test_ws_frame test/unit/test_config_yaml \
	test/unit/test_control_policy test/unit/test_stats_publication

UNIT_TESTS += test/unit/test_entropy_diag

UNIT_TESTS += test/unit/test_stats_socket
UNIT_TESTS += test/unit/test_timing_policy
UNIT_TESTS += test/unit/test_rate_psd_ring
UNIT_TESTS += test/unit/test_entropy_sampler_policy
UNIT_TESTS += test/unit/test_entropy_math
UNIT_TESTS += test/unit/test_cpu_usage
UNIT_TESTS += test/unit/test_config_value test/unit/test_config_node \
	test/unit/test_config_file test/unit/test_config_array
UNIT_TESTS += test/unit/test_config_bless_domains
.PHONY: test $(UNIT_TESTS)
test: $(UNIT_TESTS)
	@set -e; for t in $(UNIT_TESTS); do echo "--- $$t ---"; ./$$t; echo; done

test/unit/test_dist: test/unit/test_dist.c src/dist.c
	$(CC) -I include -o $@ $^ -lm

test/unit/test_core: test/unit/test_core.c src/parse.c src/dist.c
	$(CC) -I include -o $@ $^ -lm

test/unit/test_ipv6: test/unit/test_ipv6.c src/parse.c
	$(CC) -I include -o $@ $^ -lm

test/unit/test_device: test/unit/test_device.c
	$(CC) -I include -o $@ $^ -lm

test/unit/test_ws_frame: test/unit/test_ws_frame.c src/ws_frame.c
	$(CC) -I include -o $@ $^

test/unit/test_config_yaml: test/unit/test_config_yaml.c src/config_yaml.c \
		$(LIBYAML_TEST_SRC)
	$(CC) -I include $(LIBYAML_TEST_FLAGS) -o $@ $^

test/unit/test_control_policy: test/unit/test_control_policy.c src/control_policy.c
	$(CC) -I include -o $@ $^

test/unit/test_stats_publication: test/unit/test_stats_publication.c \
	src/stats_guard.c src/stats_payload.c
	$(CC) -I include -o $@ $^

test/unit/test_stats_socket: test/unit/test_stats_socket.c
	$(CC) -I include -o $@ $^ -pthread

test/unit/test_entropy_diag: test/unit/test_entropy_diag.c src/entropy_diag.c
	$(CC) -I include -o $@ $^ -lm

test/unit/test_timing_policy: test/unit/test_timing_policy.c include/timing_policy.h
	$(CC) -I include -o $@ test/unit/test_timing_policy.c

test/unit/test_rate_psd_ring: test/unit/test_rate_psd_ring.c \
	src/rate_psd_ring.c include/rate_psd.h
	$(CC) -I include -o $@ test/unit/test_rate_psd_ring.c src/rate_psd_ring.c

test/unit/test_entropy_sampler_policy: test/unit/test_entropy_sampler_policy.c \
	include/entropy_sampler_policy.h
	$(CC) -I include -o $@ test/unit/test_entropy_sampler_policy.c -lm

test/unit/test_entropy_math: test/unit/test_entropy_math.c include/entropy_math.h
	$(CC) -I include -o $@ test/unit/test_entropy_math.c -lm

test/unit/test_cpu_usage: test/unit/test_cpu_usage.c include/cpu_usage.h
	$(CC) -I include -o $@ test/unit/test_cpu_usage.c -lm

test/unit/test_config_value: test/unit/test_config_value.c src/config_value.c \
		include/config_value.h
	$(CC) -I include -o $@ test/unit/test_config_value.c src/config_value.c

test/unit/test_config_node: test/unit/test_config_node.c src/config_node.c \
		include/config_node.h include/config_yaml.h
	$(CC) -I include -o $@ test/unit/test_config_node.c src/config_node.c

test/unit/test_config_file: test/unit/test_config_file.c src/config_file.c \
		src/config_yaml.c include/config_file.h $(LIBYAML_TEST_SRC)
	$(CC) -D_GNU_SOURCE -I include $(LIBYAML_TEST_FLAGS) -o $@ \
		test/unit/test_config_file.c src/config_file.c src/config_yaml.c \
		$(LIBYAML_TEST_SRC)

test/unit/test_config_array: test/unit/test_config_array.c src/config_array.c \
		src/config_value.c src/parse.c include/config_array.h
	$(CC) -D_GNU_SOURCE -I include -o $@ test/unit/test_config_array.c \
		src/config_array.c src/config_value.c src/parse.c

test/unit/test_config_bless_domains: test/unit/test_config_bless_domains.c \
		src/config_bless_ether.c src/config_bless_vxlan.c src/config_array.c \
		src/config_node.c src/config_value.c src/config_yaml.c src/parse.c \
		$(LIBYAML_TEST_SRC)
	$(CC) -D_GNU_SOURCE -I include $(LIBYAML_TEST_FLAGS) \
		$(shell pkg-config --cflags libdpdk 2>/dev/null) -o $@ $^ \
		$(shell pkg-config --libs libdpdk 2>/dev/null)

.PHONY: integration-test
# Build CivetWeb first in an environment with networking enabled:
#   make -C third_party build-civetweb
# This target intentionally excludes libyaml/DPDK and exercises only the
# local socket fixture.
integration-test: test/integration/test_civetweb_socket
	./test/integration/test_civetweb_socket

.PHONY: integration-live
integration-live:
	python3 test/integration/test_live_control.py

test/integration/test_civetweb_socket: test/integration/test_civetweb_socket.c lib/libcivetweb.a
	$(CC) -I third_party/civetweb/build/source/include -o $@ $^ \
		-lpthread -ldl -lssl -lcrypto
